# Generated by Django 5.2 on 2025-05-25 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="content"),
                ),
                ("deadline", models.DateField(verbose_name="deadline")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("in_progress", "in_progress"),
                            ("completed", "completed"),
                        ],
                        default="created",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="tasks.task",
                        verbose_name="parent",
                    ),
                ),
                (
                    "performer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performer",
                    ),
                ),
            ],
        ),
    ]
